### ISSUE TITLE
Better reply quickly

### ISSUE THREAD

**Issue by tnix100** [catonmeower/catonmeower.github.io#1]
@catonmeower 
![164893048-b118d840-9a43-4b2c-a4d8-8f6599154df0.png](https://user-images.githubusercontent.com/61485190/164893310-e5abd7f6-4aa9-45b2-a4f6-6960af159147.png)

**Comment by catonmeower** [comment]
@tnix100

**Comment by catonmeower** [comment]
Dang notification wasn't quick ebougj
